### ISSUE TITLE
Suggestion: also add new variables in .env.example

### ISSUE THREAD

**Issue by Ant-V** [syamsoul/laravel-set-env#2]
The idea is as follows: when working on local it would be great to just have to add new .env variables once and have them added to .env.example as well, so I do not have to a) do it manually or b) forget about it when the project gets deployed and I'm hunting down errors because I forgot to add it in the .env manually after deploying...

Also an option to add them with an empty value in .example could be useful, although not necessary.

PS: Great work and idea! No longer will moderators need access to the .env file! Thanks!!

**Comment by syamsoul** [comment]
You can add variable in .env.example by passing `.env.example` in the first argument when creating `Env` instance.

```
$envService = new Env('.env.example');
$envService->set("MY_APP_NAME", "Localhost");
```

or, using Artisan command

```
php artisan souldoit:set-env "MY_APP_NAME=Localhost" --env_file_path=.env.example
```
